Repository beattosetto/beattosetto, pull requests merged in 2021-10, with the labels that each got.

#61 Fix error when import beatmap and add beatmap popup box
  .coveragerc
  .github/workflows/django.yml
  beatmap_collections/forms.py
  beatmap_collections/functions.py
  beatmap_collections/migrations/0029_auto_20211028_1813.py
  beatmap_collections/migrations/0030_auto_20211028_1919.py
  beatmap_collections/models.py
  beatmap_collections/static/css/index.css
  beatmap_collections/static/img/triangle-bpm.svg
  beatmap_collections/static/logo/osu-logo-pink.png
  beatmap_collections/static/logo/osu-logo.png
  beatmap_collections/templates/beatmap_collections/base.html
  beatmap_collections/templates/beatmap_collections/collection_page.html
  beatmap_collections/templates/beatmap_collections/snippets/beatmap_card.html
  beatmap_collections/templatetags/convert_beatmap_stat.py
  beatmap_collections/templatetags/convert_progress_bar.py
  beatmap_collections/templatetags/length_format.py
  beatmap_collections/templatetags/thousand_seperator.py
  beatmap_collections/tests.py
  requirements.txt
Labels: area:collection, area:api, area:beatmap, fix from discussion, size/XL

#93 Added licensing information to README.md
  README.md
Labels: type:documentation, size/XS

#95 Add website icon and necessary meta tag to template and change picture in info box and other place
  beatmap_collections/static/css/index.css
  beatmap_collections/static/favicon/android-chrome-192x192.png
  beatmap_collections/static/favicon/android-chrome-512x512.png
  beatmap_collections/static/favicon/apple-touch-icon.png
  beatmap_collections/static/favicon/favicon-16x16.png
  beatmap_collections/static/favicon/favicon-32x32.png
  beatmap_collections/static/favicon/favicon.ico
  beatmap_collections/static/favicon/site.webmanifest
  beatmap_collections/static/img/bpm-circle.svg
  beatmap_collections/static/img/circle-count-circle.svg
  beatmap_collections/static/img/have-video-circle.svg
  beatmap_collections/static/img/have-video-gray.svg
  beatmap_collections/static/img/slider-count-circle.svg
  beatmap_collections/static/img/spinner-count-circle.svg
  beatmap_collections/static/img/triangle-bpm.svg
  beatmap_collections/templates/beatmap_collections/add_beatmap.html
  beatmap_collections/templates/beatmap_collections/base.html
  beatmap_collections/templates/beatmap_collections/base_generic.html
  beatmap_collections/templates/beatmap_collections/collection_page.html
  beatmap_collections/templates/beatmap_collections/create_collection.html
  beatmap_collections/templates/beatmap_collections/edit_collection.html
  beatmap_collections/templates/beatmap_collections/snippets/beatmap_card.html
  users/templates/account/login.html
  users/templates/account/signup.html
  users/templates/users/settings.html
Labels: frontend, size/L
